language: python
python:
  - "3.6"      # current default Python on Travis CI

install:
  - pip install -r requirements.txt
  - cp mylims/settings.py.example mylims/settings.py
  - export SECRET=`cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1`
  - echo "SECRET_KEY='$SECRET'" >> mylims/settings.py
  - pip install coverage

script:
  - coverage run --source='.' manage.py test

after_success:
  - bash <(curl -s https://codecov.io/bash)
