# Generated by Django 2.2.27 on 2023-04-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0152_backfill_dnasequencingprocessrecord_uniquename'),
    ]

    operations = [
        migrations.AddField(
            model_name='biosampleartifact',
            name='anonymous_sample_id',
            field=models.CharField(blank=True, max_length=48, null=True, unique=True),
        ),
    ]
