# Generated by Django 2.2.27 on 2023-05-10 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0153_biosampleartifact_anonymous_sample_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biosampleartifact',
            options={'permissions': [('force_add_biosampleartifact', 'Can forcibly add a biosample artifact to Majora'), ('can_change_anonymous_sample_id', 'Can change the anonymous_sample_id of a biosample artifact')]},
        ),
    ]
