# Generated by Django 2.2.27 on 2023-05-10 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0154_auto_20230510_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biosampleartifact',
            options={'permissions': [('force_add_biosampleartifact', 'Can forcibly add a biosample artifact to Majora'), ('can_add_anonymous_sample_id', 'Can add the anonymous_sample_id of a biosample artifact'), ('can_change_anonymous_sample_id', 'Can change the anonymous_sample_id of a biosample artifact')]},
        ),
    ]
